site_name: REUSEACELL
site_description: 'REUSEACELL - Reusing 2nd life EV Batteries for stationary storage (BESS)'
site_author: 'Chris B'
docs_dir: docs/
repo_name: 'mypi-home/reuseacell'
repo_url: 'https://github.com/mypi-home/reuseacell'
nav:
    - Home: index.md
    - Page1: Page1.md
    - Approaches: Approaches.md 
    - Safety: Safety.md
    - Technical Solution: Technical_Solution.md
    - Project Example: Project_Example.md
    - How to Help: How_to_Help.md
theme:
  name: 'material'
